import logging

import aexpect

from virttest import libvirt_vm, remote, utils_params

LOG = logging.getLogger("avocado." + __name__)


def get_unprivileged_vm(vm_name, user, passwd, **args):
    """
    To get the instance of the given unprivileged vm.

    :param vm_name: name of the unprileged vm
    :param user: name of the unprivileged user
    :param passwd: password of the unprivileged user
    :param args: other arguments
    :return: instance of the unprivileged vm
    """

    host_session = aexpect.ShellSession("su")
    remote.VMManager.set_ssh_auth(host_session, "localhost", user, passwd)
    host_session.close()

    params = utils_params.Params()
    params["connect_uri"] = f"qemu+ssh://{user}@localhost/session"
    params["serials"] = args.get("serials", "serial0")
    params["status_test_command"] = args.get("status_test_command", "echo $?")
    params.update(args)
    root_dir = args.get("root_dir", f"/home/{user}/")
    addr_cache = args.get("address_cache", {})
    uvm = libvirt_vm.VM(vm_name, params, root_dir, addr_cache)

    return uvm

p = {
 'dep': [],
 'vm_type': 'libvirt',
#  'connect_uri': 'default',
 'qemu_binary': 'qemu',
 'qemu_img_binary': '/usr/bin/qemu-img',
 'qemu_io_binary': 'qemu-io',
#  'vms': 'avocado-vt-vm1',
#  'main_vm': 'avocado-vt-vm1',
 'strict_mode': 'no',
 'nics': 'nic1',
 'nettype': 'bridge',
 'netdst': 'virbr0',
 'flexible_nic_index': 'no',
 'images': 'image1',
 'image_chain': '',
 'cdroms': 'cd1',
 'usbs': 'usb1',
 'usb_type': 'qemu-xhci',
 'usb_type_usb1': 'qemu-xhci',
 'usb_max_port': '6',
 'usb_devices': 'tablet1',
 'usbdev_type_tablet1': 'usb-tablet',
 'usb_controller': 'xhci',
 'usbdev_bus': 'usb1.0',
 'serials': 'serial0',
 'serial_type': 'isa-serial',
 'smp': '2',
 'vcpu_clusters': 'INVALID',
 'vcpu_drawers': 'INVALID',
 'vcpu_books': 'INVALID',
 'mem': '2048',
 'mem_chk_re_str': '[^\\$]([0-9]+)',
 'image_size': '10G',
 'memballoon_model': 'virtio',
 'image_raw_device': 'no',
 'image_name': 'images/jeos-27-x86_64',
 'image_verify_bootable': 'yes',
 'image_unbootable_pattern': 'Hard Disk.*not a bootable disk',
 'monitors': 'qmpmonitor1',
 'chardev_backend_qmpmonitor1': 'unix_socket',
 'monitor_type': 'qmp',
 'catch_monitor': 'catch_monitor',
 'chardev_backend_catch_monitor': 'unix_socket',
 'enable_debugcon': 'yes',
 'display': 'vnc',
 'vnc_autoport': 'yes',
 'vga': 'std',
 'vga_use_legacy_expression': 'no',
 'take_regular_screendumps': 'yes',
 'keep_screendumps_on_error': 'yes',
 'keep_screendumps': 'yes',
 'screendump_delay': '5',
 'encode_video_files': 'yes',
 'vm_info_delay': '5',
 'store_vm_info': 'yes',
 'vm_info_cmds': 'registers',
 'boot_order': 'cdn',
 'boot_once': 'c',
 'boot_menu': 'off',
 'boot_strict': 'off',
 'rtc_base': 'utc',
 'rtc_clock': 'host',
 'malloc_perturb': 'no',
 'run_tcpdump': 'yes',
 'drive_index_image1': '0',
 'drive_index_cd1': '1',
 'drive_rerror_image1': '',
 'drive_werror_image1': '',
 'remove_image_image1': 'no',
 'backup_image': 'no',
 'backup_dir': 'images/',
 'backup_image_on_check_error': 'no',
 'restore_image_on_check_error': 'no',
 'restore_image': 'no',
 'skip_image_processing': 'no',
 'skip_image_check_during_running': 'no',
 'skip_cluster_leak_warn': 'no',
 'create_vm_libvirt': 'no',
 'start_vm': 'no',
 'kill_vm_before_test': 'no',
 'paused_after_start_vm': 'no',
 'kill_vm': 'yes',
 'kill_vm_gracefully': 'yes',
 'kill_unresponsive_vms': 'yes',
 'kill_timeout': '60',
 'kill_vm_libvirt': 'no',
 'kill_vm_libvirt_options': '--managed-save',
 'env_cleanup': 'no',
 'verify_host_dmesg': 'yes',
 'expected_host_dmesg': "Warning: Deprecated', 'Warning: Unmaintained",
 'verify_guest_dmesg': 'no',
 'expected_guest_dmesg': "Warning: Deprecated', 'Warning: Unmaintained",
 'guest_dmesg_level': '3',
 'guest_dmesg_ignore': 'False',
 'guest_dmesg_dump_console': 'yes',
 'convert_ppm_files_to_png': 'no',
 'keep_ppm_files': 'no',
 'keep_ppm_files_on_error': 'no',
 'screendump_quality': '30',
 'screendump_temp_dir': '/dev/shm',
 'screendump_verbose': 'no',
 'keep_video_files': 'yes',
 'keep_video_files_on_error': 'yes',
 'shell_port': '22',
 'used_cpus': '2',
 'used_mem': '512',
 'auto_cpu_model': 'yes',
 'cpu_model_flags': '',
 'redirs': 'remote_shell',
 'guest_port_remote_shell': '22',
 'profilers': 'kvm_stat',
 'login_timeout': '360',
 'test_timeout': '14400',
 'use_autostart': 'no',
 'use_check_cpu': 'yes',
 'use_debug': 'yes',
 'use_no_reboot': 'no',
 'use_os_variant': 'yes',
 'use_os_type': 'yes',
 'url_auto_ip': '',
 'use_virt_install_wait': 'no',
 'virt_install_wait_time': '300',
 'local_ip': 'ENTER.YOUR.LOCAL.EXAMPLE.COM',
 'local_pwd': '',
 'remote_ip': 'ENTER.YOUR.REMOTE.EXAMPLE.COM',
 'remote_user': 'root',
 'remote_pwd': '',
 'migration_setup': 'no',
 'migrate_source_host': 'ENTER.YOUR.SOURCE.EXAMPLE.COM',
 'migrate_source_pwd': 'PASSWORD.SOURCE.EXAMPLE',
 'migrate_dest_host': 'ENTER.YOUR.DEST.EXAMPLE.COM',
 'migrate_dest_pwd': 'PASSWORD.DEST.EXAMPLE',
 'migrate_shared_storage': 'SHARED_IMAGE.EXAMPLE',
 'migrate_vms': '',
 'migrate_main_vm': 'avocado-vt-vm1',
 'migrate_load_vms': '',
 'migrate_proto': 'tcp',
 'migrate_port': '49152',
 'netdev_peer_re': '\\s{2,}(.*?): .*?\\\\\\s(.*?):',
 'image_clone_command': 'cp --reflink=auto %s %s',
 'image_remove_command': 'rm -rf %s',
 'indirect_image_blacklist': '/dev/hda[\\d]* /dev/sda[\\d]* /dev/sg0 /dev/md0',
 'inactivity_treshold': '1800',
 'inactivity_watcher': 'log',
 'vfd_size': '1440k',
 'install_virtio': 'no',
 'cmds_installed_host': '',
 'virtinstall_extra_args': '',
 'enable_libvirtd_debug_log': 'yes',
 'libvirtd_debug_level': '2',
 'libvirtd_debug_file': '/var/lib/avocado/job-results/job-2024-06-16T23.45-eb1b378/test-results/2-type_specific.io-github-autotest-libvirt.virtual_network.qos.check_qos_floor.without_floor/libvirtd.log',
 'libvirtd_log_cleanup': 'yes',
 'enable_split_libvirtd_feature': 'no',
 'enable_host_sosreport': 'no',
 'enable_remote_host_sosreport': 'no',
 'rpmbuild_path': '/root/rpmbuild/',
 'sysprep_required': 'no',
 'sysprep_options': '--operations machine-id',
 'gcov_qemu': 'no',
 'gcov_qemu_reset': 'yes',
 'gcov_qemu_collect_cmd_opts': '--html',
 'gcov_qemu_compress': 'no',
 'stress_install_from_repo': 'no',
 'stress_args': '--cpu 4 --io 4 --vm 2 --vm-bytes 256M',
 'download_url_stress': 'stress/stress-1.0.4.tar.gz',
 'enable_guest_sosreport': 'no',
 'inputs': '',
 'gluster_managed_by_test': 'yes',
 'vm_monitor_exit_status': 'no',
 'kickstart_reboot_bug': 'no',
 'force_reset_go_down_check': 'qmp',
 'qemu_stop': 'on',
 'qemu_preconfig': 'off',
 'uuid_dimm': '',
 'subtest': 'io-github-autotest-libvirt.virtual_network.qos.check_qos_floor',
 'virt_test_type': 'libvirt',
 'provider': 'io-github-autotest-libvirt',
 'type': 'check_qos_floor',
 'timeout': '240',
 'machine_type': 'q35',
 'enable_pvpanic': 'yes',
 'ioport_pvpanic': '0x505',
 'pci_bus': 'pci.0',
 'pcie_extra_root_port': '1',
 'os_type': 'linux',
 'shutdown_command': 'shutdown -h now',
 'reboot_command': 'shutdown -r now',
 'status_test_command': 'echo $?',
 'shell_linesep': '\\n',
 'username': 'root',
 'password': 'redhat',
 'shell_client': 'ssh',
 'file_transfer_client': 'scp',
 'file_transfer_port': '22',
 'mem_chk_cmd': "dmidecode -t 17 | awk -F: '/Size/ {print $2}'",
 'mem_chk_cur_cmd': 'grep MemTotal /proc/meminfo',
 'cpu_chk_cmd': 'grep -c "^processor\\b" /proc/cpuinfo',
 'cpu_chk_all_cmd': 'lscpu | grep "^CPU(s)" | grep -o "[0-9]*"',
 'cdrom_get_cdrom_cmd': 'ls /dev/cdrom*',
 'cdrom_check_cdrom_pattern': '/dev/cdrom-\\w+|/dev/cdrom\\d*',
 'cdrom_test_cmd': 'dd if=%s of=/dev/null bs=1 count=1',
 'cdrom_info_cmd': 'cat /proc/sys/dev/cdrom/info',
 'vm_arch_name': 'x86_64',
 'os_variant': 'rhel9.4',
 'boot_path': 'images/pxeboot',
 'nic_model': 'virtio',
 'enable_msix_vectors': 'yes',
 'drive_format': 'virtio',
 'cd_format': 'ahci',
 'image_boot': 'yes',
 'image_format': 'qcow2',
 'check_image': 'yes',
 'pci_assignable': 'no',
 'image_backend': 'filesystem',
 'virt_install_binary': '/usr/bin/virt-install',
 'hvm_or_pv': 'hvm',
 'backup_image_before_testing': 'yes',
 'restore_image_after_testing': 'yes',
}